openapi: 3.0.0

info:
  version: 1.0.0
  title: OpenAPI Service

paths: {}

components:
  schemas:
    ErrorResponse:
      required:
        - message
      properties:
        message:
          type: string

    PeopleResponse:
      required:
        - data
      properties:
        data:
          $ref: "#/components/schemas/Person"

    Person:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        contact:
          $ref: "#/components/schemas/Contact"
        employment:
          $ref: "#/components/schemas/Employment"
      required:
        - id
        - firstName
        - lastName

    Contact:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string
      required:
        - email
        - phone

    Employment:
      type: object
      properties:
        department:
          type: string
        position:
          type: string

    ContactFields:
      type: array
      items:
        type: string
        enum: [email, phone]

    EmploymentFields:
      type: array
      items:
        type: string
        enum: [department, position]

    PersonFields:
      type: object
      properties:
        contact:
          $ref: "#/components/schemas/ContactFields"
        employment:
          $ref: "#/components/schemas/EmploymentFields"
